---
- name: Install k3s and configure kubeconfig
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Install k3s using official script
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .k3s directory exists in home
      become: false
      file:
        path: "{{ lookup('env','HOME') }}/.k3s"
        state: directory
        mode: '0755'

    - name: Copy k3s.yaml to user's .k3s directory
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','HOME') }}/.k3s/k3s.yaml"
        remote_src: yes
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: '0644'

    - name: Set KUBECONFIG environment variable in .bashrc
      lineinfile:
        path: "{{ lookup('env','HOME') }}/.bashrc"
        line: 'export KUBECONFIG=$HOME/.k3s/k3s.yaml'
        state: present
      become: false

    - name: Enable kubectl autocompletion in .bashrc
      lineinfile:
        path: "{{ lookup('env','HOME') }}/.bashrc"
        line: 'source <(kubectl completion bash)'
        state: present
      become: false

    - name: Add kubectl alias to .bashrc
      lineinfile:
        path: "{{ lookup('env','HOME') }}/.bashrc"
        line: 'alias k=kubectl'
        state: present
      become: false

    - name: Add kubectl completion for alias k to .bashrc
      lineinfile:
        path: "{{ lookup('env','HOME') }}/.bashrc"
        line: 'complete -F __start_kubectl k'
        state: present
      become: false

    - name: Display all pods in all namespaces
      shell: kubectl get pod -A
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.k3s/k3s.yaml"
      register: pods_output
      changed_when: false

    - name: Install Helm using official script
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add elastic Helm repo
      shell: helm repo add elastic https://helm.elastic.co
      args:
        creates: "{{ lookup('env','HOME') }}/.cache/helm/repository/elastic-index.yaml"
      become: false

    - name: Update Helm repos
      shell: helm repo update
      become: false
